### ISSUE TITLE
Need to improve

### ISSUE THREAD

**Issue by UnknownNull** [ReinfyTeam/Zuri#21]
Some checks are very sensitive and misdiagnosed, and others are not accurate!

Misdiagnosis:
- omnisprint
- airmovement
- timer

Non-check:
- speed
- reach

Video for example:
https://cdn.discordapp.com/attachments/1217426651181351035/1217428123067351150/Minecraft_2024..mp4?ex=6603fd4b&is=65f1884b&hm=053976a192af92e6497306f1aa596c269869ad9bffb29b8107cde82020e3d9a7&

**Comment by rodolfoorlandajr** [comment]
I see, if you are willing to improve our plugin, you're welcome to submit your pull requests, also don't create so bunch of pull requests with one commit everytime. Try to use `git`, or `github` application to commit in a branch.

**Comment by rodolfoorlandajr** [comment]
Reach is now working as expected.

**Comment by UnknownNull** [comment]
> Reach is now working as expected.

```
Error: Call to a member function isCreative() on null
File: plugins/Zuri-main/src/ReinfyTeam/Zuri/checks/blockbreak/WrongMining
Line: 61
```

**Comment by xRodzMC** [comment]
> > Reach is now working as expected.
> 
> ```
> Error: Call to a member function isCreative() on null
> File: plugins/Zuri-main/src/ReinfyTeam/Zuri/checks/blockbreak/WrongMining
> Line: 61
> ```

This should fixed in latest commit.

**Comment by xRodzMC** [comment]
Also there's nothing wrong now in `AirMovement` it seems it is working.

**Comment by xRodzMC** [comment]
> Some checks are very sensitive and misdiagnosed, and others are not accurate!
> 
> Misdiagnosis:
> 
> * omnisprint
> * airmovement
> * timer
> 
> Non-check:
> 
> * speed
> * reach
> 
> Video for example: https://cdn.discordapp.com/attachments/1217426651181351035/1217428123067351150/Minecraft_2024..mp4?ex=6603fd4b&is=65f1884b&hm=053976a192af92e6497306f1aa596c269869ad9bffb29b8107cde82020e3d9a7&

Speed and Reach were fixed. Omnisprints needs to be improve soon...

**Comment by UnknownNull** [comment]
In the new update, players cannot damage each other

**Comment by xRodzMC** [comment]
> In the new update, players cannot damage each other

Are you using with other plugins? Specially a plugin that uses `EntityDamageEvent`?

**Comment by UnknownNull** [comment]
I fixed it by changing the rules of the world

**Comment by UnknownNull** [comment]
new:
If a server uses the economyland plugin and a player is transferred from a command to move from a land to another land that does not load the chunk, it will fall from the sky and this will cause the anti-cheat to mistakenly recognize a fly cheat.

**Comment by xRodzMC** [comment]
> new: If a server uses the economyland plugin and a player is transferred from a command to move from a land to another land that does not load the chunk, it will fall from the sky and this will cause the anti-cheat to mistakenly recognize a fly cheat.

chunk issue 🤔

**Comment by xRodzMC** [comment]
> new: If a server uses the economyland plugin and a player is transferred from a command to move from a land to another land that does not load the chunk, it will fall from the sky and this will cause the anti-cheat to mistakenly recognize a fly cheat.

Fixed in commit: https://github.com/ReinfyTeam/Zuri/commit/9ea61ba7bceb2adfe6333f8da0bcec90253f8583

**Comment by xRodzMC** [comment]
Omnisprint were fixed.
