### ISSUE TITLE
Spamming bow triggers Scaffold (E)

### ISSUE THREAD

**Issue by TrinitroToluen0** [ReinfyTeam/Zuri#25]
To reproduce:
1. Get a bow and arrows
2. Spam right click
3. See how Zuri alerts of scaffold

**Comment by xRodzMC** [comment]
Please provide the following details:

Version that you are currently using: (ex. 1.1.6)
Expected: (what is actually you will expect)
Unexpected: (what is actually happend.)
Attachment: (use pictures/screenshots or video/screen-recordings to much detail your issue. As much possible use `/zuri debug` in most cases.)
Module and Subtype: (ex. AimAssist (A))

**Comment by xRodzMC** [comment]
Fixed in https://github.com/ReinfyTeam/Zuri/commit/a29cb0f45e305c87442472bedc22c5c85a51a453, Thanks for Reporting!
