### ISSUE TITLE
Server crashes when shooting bow

### ISSUE THREAD

**Issue by TrinitroToluen0** [ReinfyTeam/Zuri#26]
ZURI VERSION: Dev build 5 (4c98384b693b9414245fd036ff3b08f579f46c0b)
PM VERSION: Latest

To reproduce:
1. Shoot a bow

You guys have really made a great job, but i suggest having a "test" world to test all the players movements and packets after each update, I am using Zuri rewrite dev 94 with Scaffold (E) disabled, because none of the other next versions are stable, not even the 1.2.0 release, they just crash.

2024-04-09 [09:10:32.153] [Server thread/CRITICAL]: ErrorException: "Undefined array key 0" (EXCEPTION) in "plugins/Zuri_dev-5.phar/src/checks/combat/FastBow" at line 83
--- Stack trace ---
  #0 plugins/Zuri_dev-5.phar/src/checks/combat/FastBow(83): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 0, string[78] phar:///home/admin/Server/plugins/Zuri_dev-5.phar/src/checks/combat/FastBow.php, int 83)
  #1 plugins/Zuri_dev-5.phar/src/listener/PlayerListener(519): ReinfyTeam\Zuri\checks\combat\FastBow->checkEvent(object pocketmine\event\entity\EntityShootBowEvent#271624, object ReinfyTeam\Zuri\player\PlayerAPI#46362)
  #2 plugins/Zuri_dev-5.phar/src/listener/PlayerListener(478): ReinfyTeam\Zuri\listener\PlayerListener->checkEvent(object pocketmine\event\entity\EntityShootBowEvent#271624, object pocketmine\player\Player#46410)
  #3 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onEntityShootBowEvent(object pocketmine\event\entity\EntityShootBowEvent#271624)
  #4 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityShootBowEvent#271624)
  #5 pmsrc/src/item/Bow(92): pocketmine\event\Event->call()
  #6 pmsrc/src/player/Player(1678): pocketmine\item\Bow->onReleaseUsing(object pocketmine\player\Player#46410, array[0])
  #7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(575): pocketmine\player\Player->releaseHeldItem()
  #8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(344): pocketmine\network\mcpe\handler\InGamePacketHandler->handleReleaseItemTransaction(object pocketmine\network\mcpe\protocol\types\inventory\ReleaseItemTransactionData#250059)
  #9 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(94): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#322709)
  #10 pmsrc/src/network/mcpe/NetworkSession(468): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#222402)
  #11 plugins/FixServerCrash_dev-11.phar/src/Zwuiix/FixServerCrash/network/CustomNetworkSession(201): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#322709, string[36] .........................-.....Br...)
  #12 plugins/FixServerCrash_dev-11.phar/src/Zwuiix/FixServerCrash/network/CustomRakLibInterface(92): Zwuiix\FixServerCrash\network\CustomNetworkSession->handleEncoded(string[58] .S.c`a``x...$....`...C._w;..t........ ... .0L)H......#....)
  #13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): Zwuiix\FixServerCrash\network\CustomRakLibInterface->onPacketReceive(int 0, string[67] ....c[:.b..<...:.1...'y..gh..Q1)...c.U....Xevq...'..+*Rr.4..\.5g34.)
  #14 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object Zwuiix\FixServerCrash\network\CustomRakLibInterface#46194)
  #15 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #17 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #18 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #19 pmsrc/src/Server(1696): pocketmine\snooze\SleeperHandler->sleepUntil(float 1712653832.179)
  #20 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #21 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[18] /home/admin/Server/, string[26] /home/admin/Server/plugins/)
  #22 pmsrc/src/PocketMine(378): pocketmine\server()
  #23 /home/admin/Server/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMP1a1dZ0.tar/src/PocketMine.php)
--- End of exception information ---

**Comment by xRodzMC** [comment]
Fixed in https://github.com/ReinfyTeam/Zuri/commit/89497f880acddb55327cb81dc38ff9e259b0acf6, Thanks for reporting!
