### ISSUE TITLE
Please test your builds

### ISSUE THREAD

**Issue by TrinitroToluen0** [ReinfyTeam/Zuri#27]
ZURI VERSION: Dev build #9 (f32a459ac524514e2f943e3cae77752dd2ceba4a)
PM VERSION: Latest

To reproduce:
1. Join your server with Zuri installed.

2024-04-09 [19:07:31.484] [Server thread/CRITICAL]: TypeError: "ReinfyTeam\Zuri\checks\Check::enable(): Return value must be of type bool, null returned" (EXCEPTION) in "plugins/Zuri_dev-9.phar/src/checks/Check" at line 50
--- Stack trace ---
  #0 plugins/Zuri_dev-9.phar/src/listener/PlayerListener(539): ReinfyTeam\Zuri\checks\Check->enable()
  #1 plugins/Zuri_dev-9.phar/src/listener/PlayerListener(341): ReinfyTeam\Zuri\listener\PlayerListener->checkJustEvent(object pocketmine\event\player\PlayerPreLoginEvent#221187)
  #2 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onPlayerPreLogin(object pocketmine\event\player\PlayerPreLoginEvent#221187)
  #3 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerPreLoginEvent#221187)
  #4 pmsrc/src/network/mcpe/handler/LoginPacketHandler(136): pocketmine\event\Event->call()
  #5 pmsrc/vendor/pocketmine/bedrock-protocol/src/LoginPacket(115): pocketmine\network\mcpe\handler\LoginPacketHandler->handleLogin(object pocketmine\network\mcpe\protocol\LoginPacket#63598)
  #6 pmsrc/src/network/mcpe/NetworkSession(468): pocketmine\network\mcpe\protocol\LoginPacket->handle(object pocketmine\network\mcpe\handler\LoginPacketHandler#221138)
  #7 plugins/FixServerCrash_dev-11.phar/src/Zwuiix/FixServerCrash/network/CustomNetworkSession(201): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\LoginPacket#63598, string[121029] ............{"chain":["eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGS)
  #8 plugins/FixServerCrash_dev-11.phar/src/Zwuiix/FixServerCrash/network/CustomRakLibInterface(92): Zwuiix\FixServerCrash\network\CustomNetworkSession->handleEncoded(string[26698] ......H./....q..W....I@..w.H..D+.L!9..!....*.. ._..~........ke......z...of...5S.)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): Zwuiix\FixServerCrash\network\CustomRakLibInterface->onPacketReceive(int 0, string[26699] .......H./....q..W....I@..w.H..D+.L!9..!....*.. ._..~........ke......z...of...5S)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object Zwuiix\FixServerCrash\network\CustomRakLibInterface#220990)
  #11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #13 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1696): pocketmine\snooze\SleeperHandler->sleepUntil(float 1712689651.5024)
  #16 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[18] /home/admin/Server/, string[26] /home/admin/Server/plugins/)
  #18 pmsrc/src/PocketMine(378): pocketmine\server()
  #19 /home/admin/Server/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPTQKKpm.tar/src/PocketMine.php)
--- End of exception information ---

**Comment by xRodzMC** [comment]
Your configuration might outdated, considering removing the old configuration first.
