### ISSUE TITLE
Check Ideas

### ISSUE THREAD

**Issue by DanteDEVS** [ReinfyTeam/Zuri#28]
- GhostHand
- Hitbox

**Comment by xRodzMC** [comment]
Good idea! I'll do this in next version! Thanks for your suggestion!

**Comment by xRodzMC** [comment]
HitBox might impossible due to we can't actually calculate the bounding box within the entity, but i'll try my best to do it.

**Comment by xRodzMC** [comment]
Closing this to migrate issue to #40
