### ISSUE TITLE
Call to a member function getName() on null 2

### ISSUE THREAD

**Issue by UnknownNull** [ReinfyTeam/Zuri#33]
Error: Call to a member function getName() on null
File: plugins/Zuri-main/src/listener/PlayerListener
Line: 506
Type: Error
Backtrace:
```
#0 plugins/Zuri-main/src/listener/PlayerListener(97): ReinfyTeam\Zuri\listener\PlayerListener->getCPS(object ReinfyTeam\Zuri\player\PlayerAPI#2055540)
#1 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#1946557)
#2 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent#1946557)
```

**Comment by rodolfoorlandajr** [comment]
I cannot reproduce the issue.

**Comment by rodolfoorlandajr** [comment]
Please reproduce the issue and record it so i can track the issue.

**Comment by rodolfoorlandajr** [comment]
Is there any update? Is your problem fixed?

**Comment by UnknownNull** [comment]
I removed the anti-cheat from my server and replaced the authentication method with a mobile number so that the player has no way to log in after being banned except with a new mobile number (anti-cheats full of bugs don't work anymore)

**Comment by rodolfoorlandajr** [comment]
> I removed the anti-cheat from my server and replaced the authentication method with a mobile number so that the player has no way to log in after being banned except with a new mobile number (anti-cheats full of bugs don't work anymore)

It works fine to me, without any plugins.

**Comment by rodolfoorlandajr** [comment]
Closing this as stale.
