### ISSUE TITLE
Crashes when I leave the server

### ISSUE THREAD

**Issue by Egehanss** [ReinfyTeam/Zuri#34]
`
[Server thread/CRITICAL]: Error: "Class "ReinfyTeam\Zuri\APIProvider" not found" (EXCEPTION) in "plugins/Zuri.phar/src/utils/discord/Discord" at line 138
--- Stack trace ---
  #0 plugins/Zuri.phar/src/utils/discord/Discord(63): ReinfyTeam\Zuri\utils\discord\Discord::getWebhookConfig()
  #1 plugins/Zuri.phar/src/listener/ServerListener(68): ReinfyTeam\Zuri\utils\discord\Discord::Send(object ReinfyTeam\Zuri\player\PlayerAPI#112732, int 3)
  #2 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\ServerListener->onPlayerQuit(object pocketmine\event\player\PlayerQuitEvent#75563)
  #3 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent#75563)
  #4 pmsrc/src/player/Player(2241): pocketmine\event\Event->call()
  #5 pmsrc/src/network/mcpe/NetworkSession(812): pocketmine\player\Player->onPostDisconnect(object pocketmine\lang\Translatable#98945, null)
  #6 pmsrc/src/network/mcpe/NetworkSession(703): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #7 pmsrc/src/network/mcpe/NetworkSession(810): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#74475, object pocketmine\lang\Translatable#98945)
  #8 pmsrc/src/network/mcpe/raklib/RakLibInterface(165): pocketmine\network\mcpe\NetworkSession->onClientDisconnect(object pocketmine\lang\Translatable#98945)
  #9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(72): pocketmine\network\mcpe\raklib\RakLibInterface->onClientDisconnect(int 0, int 0)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#48350)
  #11 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #13 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1696): pocketmine\snooze\SleeperHandler->sleepUntil(float 1714575706.5081)
  #16 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[45] C:\Users\Administrator\Desktop\Kobat Faction\, string[53] C:\Users\Administrator\Desktop\Kobat Faction\plugins\)
  #18 pmsrc/src/PocketMine(378): pocketmine\server()
  #19 C:/Users/Administrator/Desktop/Kobat Faction/PocketMine-MP.phar(168): require(string[112] phar://C:/Users/Administrator/AppData/Local/Temp/2/PocketMine-MP-phar-cache.0/PM)`

**Comment by rodolfoorlandajr** [comment]
What version are you using? Is this your zuri is outdated?

**Comment by Egehanss** [comment]
It was latest release on the poggit.

**Comment by rodolfoorlandajr** [comment]
Please use [github releases](https://github.com/ReinfyTeam/Zuri/releases/tag/v1.2.1) or poggit ci, If you we're any encountered any bugs and issues. Poggit releases are delayed due to they need to approve it first before it is published through their website. This is probably fix for commit https://github.com/ReinfyTeam/Zuri/commit/49ad72923b8353fddc1418e4bdf309e319cefd73 for poggit release.
