### ISSUE TITLE
Proxy..

### ISSUE THREAD

**Issue by GabBiswajit** [ReinfyTeam/Zuri#43]
I use this plugin in my proxy server and when player join it's showing the proxy ipv not player ipv in (waterdog) and thats why this plugin kill players more than 3 due to ip limits please do somthing..

**Comment by rodolfoorlandajr** [comment]
Well, i am now currently investigating the problem, for now disable the proxy for your server, until the issue once fixed.

**Comment by ItsToxicGG** [comment]
use something like wdpeipfixer

**Comment by rodolfoorlandajr** [comment]
> https://github.com/supercrafter333/WaterdogPE-IP-XUID-Fixer like this (old)
> 
> heres a latest one https://github.com/xxAROX/WaterdogPE-LoginExtras-Fix

I reconsider this one to use if you are using the proxy (waterdogpe). This is will not be fixed in the anticheat since this is only intended for PocketMine-MP native feature itself.

**Comment by rodolfoorlandajr** [comment]
The network ip limit will be now optional in the configuration in the incoming major release.

**Comment by GabBiswajit** [comment]
@ItsToxicGG it also not work when I try to connect with proxy it's not connecting.
