### ISSUE TITLE
Problem when a player logs server in with EditionFaker

### ISSUE THREAD

**Issue by b1zeyofficial** [ReinfyTeam/Zuri#52]
I encountered a problem when a player logs in using EditionFaker, the server goes down due to a crash.
Used Horion for the test
Minecraft version: 1.21.21
Zuri plugin version: latest from GitHub

PocketMine-MP Crash Dump Tue Sep 3 09:33:11 UTC 2024

PocketMine-MP version: 5.18.1+dev [Protocol 712]
Git commit: 0000000000000000000000000000000000000000
PHP version: 8.3.4
OS: WINNT, win

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Zuri

Thread: Main
Error: ReinfyTeam\Zuri\player\PlayerAPI::getAPIPlayer(): Argument #1 ($player) must be of type pocketmine\player\Player, string given, called in C:\Users\Ozgoc\OneDrive\Рабочий стол\pocketmine\plugins\Zuri-main\src\utils\ReplaceText.php on line 66
File: plugins/Zuri-main/src/player/PlayerAPI
Line: 52
Type: TypeError
Backtrace:
#0 plugins/Zuri-main/src/utils/ReplaceText(66): ReinfyTeam\Zuri\player\PlayerAPI::getAPIPlayer(string[12] GeHePaJLAdam)
#1 plugins/Zuri-main/src/checks/Check(234): ReinfyTeam\Zuri\utils\ReplaceText::replace(string[12] GeHePaJLAdam, string[101] {prefix} ..l..7[..eWARNING..7] ..r..f{player_name} ..7is tried using ..f{module}, string[7] AntiBot, string[1] A)
#2 plugins/Zuri-main/src/checks/network/antibot/AntiBotA(60): ReinfyTeam\Zuri\checks\Check->warn(string[12] GeHePaJLAdam)
#3 plugins/Zuri-main/src/listener/PlayerListener(521): ReinfyTeam\Zuri\checks\network\antibot\AntiBotA->checkJustEvent(object pocketmine\event\player\PlayerPreLoginEvent#178512)
#4 plugins/Zuri-main/src/listener/PlayerListener(324): ReinfyTeam\Zuri\listener\PlayerListener->checkJustEvent(object pocketmine\event\player\PlayerPreLoginEvent#178512)
#5 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onPlayerPreLogin(object pocketmine\event\player\PlayerPreLoginEvent#178512)
#6 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerPreLoginEvent#178512)
#7 pmsrc/src/network/mcpe/handler/LoginPacketHandler(136): pocketmine\event\Event->call()
#8 pmsrc/vendor/pocketmine/bedrock-protocol/src/LoginPacket(115): pocketmine\network\mcpe\handler\LoginPacketHandler->handleLogin(object pocketmine\network\mcpe\protocol\LoginPacket#178615)
#9 pmsrc/src/network/mcpe/NetworkSession(469): pocketmine\network\mcpe\protocol\LoginPacket->handle(object pocketmine\network\mcpe\handler\LoginPacketHandler#196637)
#10 pmsrc/src/network/mcpe/NetworkSession(407): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\LoginPacket#178615, string[42832] ............{"chain":["eyJhbGciOiJFUzM4NCIsIng1dSI6Ik1IWXdFQVlIS29aSXpqMENBUVlGS)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[8317] ..}.r...f..<.0w;b..w.2U....DB.....91.......[.~..G..9W'..f......m.....EF7..d.o.|k)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[8318] ...}.r...f..<.0w;b..w.2U....DB.....91.......[.~..G..9W'..f......m.....EF7..d.o.|)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#179133)
#14 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
#16 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#18 pmsrc/src/Server(1698): pocketmine\snooze\SleeperHandler->sleepUntil(float 1725355991.9709)
#19 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
#20 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[59] C:\Users\Ozgoc\OneDrive\.............. ........\pocketmine\, string[67] C:\Users\Ozgoc\OneDrive\.............. ........\pocketmine\plugins\)
#21 pmsrc/src/PocketMine(378): pocketmine\server()
#22 C:/Users/Ozgoc/OneDrive/Рабочий стол/pocketmine/PocketMine-MP.phar(168): require(string[102] phar://C:/Users/Ozgoc/AppData/Local/Temp/PocketMine-MP-phar-cache.0/PMMCB56.tmp.)

Code:
[43] use function abs;
[44] use function count;
[45] use function microtime;
[46] use function spl_object_id;
[47] 
[48] class PlayerAPI implements IPlayerAPI {
[49] 	/** @var PlayerAPI[] */
[50] 	public static array $players = [];
[51] 
[52] 	public static function getAPIPlayer(Player $player) : PlayerAPI {
[53] 		return self::$players[spl_object_id($player)] ??= new PlayerAPI($player);
[54] 	}
[55] 
[56] 	public static function removeAPIPlayer(Player $player) : void {
[57] 		unset(self::$players[spl_object_id($player)]);
[58] 	}
[59] 
[60] 	private bool $isCaptcha = false;
[61] 	private bool $flagged = false;
[62] 	private bool $actionBreakingSpecial = false;

**Comment by rodolfoorlandajr** [comment]
Fixed in latest commit, you should now download latest poggit builds or in github actions.
