### ISSUE TITLE
BUG: unexpected identifier "NULL_MODELS", expecting "=""

### ISSUE THREAD

**Issue by S3b4sM** [ReinfyTeam/Zuri#53]
Hello, I have encountered several bugs when putting the plugin on my server

```
syntax error, unexpected identifier "NULL_MODELS", expecting "="" (EXCEPTION) in "plugins/Zuri/src/checks/network/editionfaker/EditionFakerA" at line 54

syntax error, unexpected identifier "PREFIX", expecting "=" in plugins/Zuri.phar/src/config/ConfigPaths
```
version pocketmine: 5.19.0 / minecraft 1.21.30

**Comment by rodolfoorlandajr** [comment]
Zuri is recently upgraded to latest php binary compability. Your php binaries might outdated. The constant type declarations are now supported in php `8.3.x`. You can view this [article](https://www.php.net/manual/en/language.types.declarations.php) about declaration types.

**Comment by Gaprix** [comment]
Official PMMP docker images use PHP 8.2

**Comment by xRodzMC** [comment]
> Official PMMP docker images use PHP 8.2

You should refer to latest php binaries pre-build pmmp [here](https://github.com/pmmp/PHP-Binaries/tags).
