### ISSUE TITLE
problems starting server

### ISSUE THREAD

**Issue by Totolas** [ReinfyTeam/Zuri#54]
Hello, every time I want to start the server with the plugin I get an error in the file packages, I don't know how to solve this
The error I get is this:
 --- Stack trace ---
  #0 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[34] ReinfyTeam\Zuri\config\ConfigPaths)
  #1 plugins/Zuri (1).phar/src/config/ConfigManager(43): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[34] ReinfyTeam\Zuri\config\ConfigPaths)
  #2 pmsrc/src/thread/ThreadSafeClassLoader(133): include(string[73] phar:///home/container/plugins/Zuri (1).phar/src/config/ConfigManager.php)
  #3 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[36] ReinfyTeam\Zuri\config\ConfigManager)
  #4 plugins/Zuri (1).phar/src/ZuriAC(124): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[36] ReinfyTeam\Zuri\config\ConfigManager)
  #5 pmsrc/src/plugin/PluginBase(77): ReinfyTeam\Zuri\ZuriAC->onLoad()
  #6 pmsrc/src/plugin/PluginManager(216): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#52906, object pocketmine\Server#13, object pocketmine\plugin\PluginDescription#50339, string[32] /home/container/plugin_data/Zuri, string[44] phar:///home/container/plugins/Zuri (1).phar, object pocketmine\plugin\DiskResourceProvider#50347)
  #7 pmsrc/src/plugin/PluginManager(368): pocketmine\plugin\PluginManager->internalLoadPlugin(string[37] /home/container/plugins/Zuri (1).phar, object pocketmine\plugin\PharPluginLoader#52906, object pocketmine\plugin\PluginDescription#50339)
  #8 pmsrc/src/Server(1018): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
  #9 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
  #10 pmsrc/src/PocketMine(378): pocketmine\server()
  #11 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPp3vtXq.tar/src/PocketMine.php)
--- End of exception information ---

**Comment by ItsToxicGG** [comment]
Hi there, i cant get this error my side, you might want to check for issues your side, like configuration issues, corrupted files (doubt), etc, Either way i do not recommend if you ran this plugin open-source, rather download it here at releases or here https://poggit.pmmp.io/p/Zuri/1.3.1

**Comment by ItsToxicGG** [comment]
Could you possibly provide the host you might be using and if you possibly using nethergames pmmp or nah?

**Comment by rodolfoorlandajr** [comment]
Can you provide the full crashdump?

**Comment by rodolfoorlandajr** [comment]
Any updates?

**Comment by rodolfoorlandajr** [comment]
Closing this as stale.
