### ISSUE TITLE
Elytra: Item non existing error constant.

### ISSUE THREAD

**Issue by blob83** [ReinfyTeam/Zuri#55]
[Server thread/CRITICAL]: Error: "Undefined constant pocketmine\item\ItemTypeIds::ELYTRA" (EXCEPTION) in "plugins/Zuri_dev-69.phar/src/checks/moving/Glide" at line 63
--- Stack trace ---
  #0 plugins/Zuri_dev-69.phar/src/listener/PlayerListener(515): ReinfyTeam\Zuri\checks\moving\Glide->checkEvent(object pocketmine\event\player\PlayerMoveEvent#122129, object ReinfyTeam\Zuri\player\PlayerAPI#200821)
  #1 plugins/Zuri_dev-69.phar/src/listener/PlayerListener(120): ReinfyTeam\Zuri\listener\PlayerListener->checkEvent(object pocketmine\event\player\PlayerMoveEvent#122129, object pocketmine\player\Player#183289)
  #2 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onPlayerMove(object pocketmine\event\player\PlayerMoveEvent#122129)
  #3 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerMoveEvent#122129)
  #4 pmsrc/src/player/Player(1342): pocketmine\event\Event->call()
  #5 pmsrc/src/player/Player(1435): pocketmine\player\Player->processMostRecentMovements()
  #6 pmsrc/src/world/World(997): pocketmine\player\Player->onUpdate(int 3871)
  #7 pmsrc/src/world/World(922): pocketmine\world\World->actuallyDoTick(int 3871)
  #8 pmsrc/src/world/WorldManager(347): pocketmine\world\World->doTick(int 3871)
  #9 pmsrc/src/Server(1813): pocketmine\world\WorldManager->tick(int 3871)
  #10 pmsrc/src/Server(1695): pocketmine\Server->tick()
  #11 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #12 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[43] C:\Users\bluer\Desktop\PHP-Windows-x64-PM5\, string[51] C:\Users\bluer\Desktop\PHP-Windows-x64-PM5\plugins\)
  #13 pmsrc/src/PocketMine(378): pocketmine\server()
  #14 C:/Users/bluer/Desktop/PHP-Windows-x64-PM5/PocketMine-MP.phar(168): require(string[102] phar://C:/Users/bluer/AppData/Local/Temp/PocketMine-MP-phar-cache.0/PMM199C.tmp.)
--- End of exception information ---

**Comment by xRodzMC** [comment]
Fixed in #57
