### ISSUE TITLE
Crashes when starting the server

### ISSUE THREAD

**Issue by PSYCHO1512** [ReinfyTeam/Zuri#56]
PocketMine-MP Crash Dump Fri Dec 13 13:27:35 UTC 2024

PocketMine-MP version: 5.23.1 [Protocol 766]
Git commit: 2b0daebc2a72784d6ea1744d6b0b91e7ab66baba
PHP version: 8.2.25
OS: Linux, linux

THIS CRASH WAS CAUSED BY A PLUGIN

Thread: Main
Error: syntax error, unexpected identifier "PREFIX", expecting "="
File: plugins/Zuri.phar/src/config/ConfigPaths
Line: 35
Type: ParseError
Backtrace:
#0 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[34] ReinfyTeam\Zuri\config\ConfigPaths)
#1 plugins/Zuri.phar/src/config/ConfigManager(43): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[34] ReinfyTeam\Zuri\config\ConfigPaths)
#2 pmsrc/src/thread/ThreadSafeClassLoader(133): include(string[69] phar:///home/container/plugins/Zuri.phar/src/config/ConfigManager.php)
#3 pmsrc/src/thread/ThreadSafeClassLoader(123): pocketmine\thread\ThreadSafeClassLoader->loadClass(string[36] ReinfyTeam\Zuri\config\ConfigManager)
#4 plugins/Zuri.phar/src/ZuriAC(124): pocketmine\thread\ThreadSafeClassLoader->pocketmine\thread\{closure}(string[36] ReinfyTeam\Zuri\config\ConfigManager)
#5 pmsrc/src/plugin/PluginBase(77): ReinfyTeam\Zuri\ZuriAC->onLoad()
#6 pmsrc/src/plugin/PluginManager(223): pocketmine\plugin\PluginBase->__construct(object pocketmine\plugin\PharPluginLoader#55824, object pocketmine\Server#13, object pocketmine\plugin\PluginDescription#53349, string[32] /home/container/plugin_data/Zuri, string[40] phar:///home/container/plugins/Zuri.phar, object pocketmine\plugin\DiskResourceProvider#53684)
#7 pmsrc/src/plugin/PluginManager(375): pocketmine\plugin\PluginManager->internalLoadPlugin(string[33] /home/container/plugins/Zuri.phar, object pocketmine\plugin\PharPluginLoader#55824, object pocketmine\plugin\PluginDescription#53349)
#8 pmsrc/src/Server(1049): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/, int 0)
#9 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#10 pmsrc/src/PocketMine(378): pocketmine\server()
#11 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPGt5fPq.tar/src/PocketMine.php)

Code:
[26]  *
[27]  *
[28]  */
[29] 
[30] declare(strict_types=1);
[31] 
[32] namespace ReinfyTeam\Zuri\config;
[33] 
[34] abstract class ConfigPaths {
[35] 	public const string PREFIX = "zuri.prefix";
[36] 
[37] 	public const string ANTIBOT_MESSAGE = "zuri.antibot.message";
[38] 	public const string EDITIONFAKER_MESSAGE = "zuri.editionfaker.message";
[39] 
[40] 	public const string NETWORK_LIMIT = "zuri.network.limit";
[41] 	public const string NETWORK_LIMIT_ENABLE = "zuri.network.enable";
[42] 	public const string NETWORK_MESSAGE = "zuri.network.message";
[43] 
[44] 	public const string PING_NORMAL = "zuri.ping.normal";
[45] 	public const string PING_LAGGING = "zuri.ping.lagging";

Loaded plugins:
CustomShopUI 5.0.5 by  for API(s) 5.0.0
theSpawn 2.0.5 by supercrafter333 for API(s) 5.0.0

uname -a: Linux 2066594c-7822-4738-b558-dbb40750d2dc 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64
Zend version: 4.2.25
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.12.1@f510c0a40911935b77b86859eb5223d58d660df1
- daverandom/callback-validator unknown@unknown
- netresearch/jsonmapper v5.0.0@8c64d8d444a5d764c641ebe97e0e3bc72b25bf6c
- pocketmine/bedrock-block-upgrade-schema 5.0.0@20dd5c11e9915bacea4fe2cf649e1d23697a6e52
- pocketmine/bedrock-data 2.15.0+bedrock-1.21.50@6e819f36d781866ce63d2406be2ce7f2d1afd9ad
- pocketmine/bedrock-item-upgrade-schema 1.14.0@9fc7c9bbb558a017395c1cb7dd819c033ee971bb
- pocketmine/bedrock-protocol 35.0.0+bedrock-1.21.50@bd1ec79bae8c88aa984e1c5f0c3313be5ae9b435
- pocketmine/binaryutils 0.2.6@ccfc1899b859d45814ea3592e20ebec4cb731c84
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/color 0.3.1@a0421f1e9e0b0c619300fb92d593283378f6a5e1
- pocketmine/errorhandler 0.7.0@cae94884368a74ece5294b9ff7fef18732dcd921
- pocketmine/locale-data 2.22.0@aed64e9ca92ffbb20788b3b3bb75b60e4f0eae2d
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/math 1.0.0@dc132d93595b32e9f210d78b3c8d43c662a5edbf
- pocketmine/nbt 1.0.0@20540271cb59e04672cb163dca73366f207974f1
- pocketmine/pocketmine-mp dev-stable@2b0daebc2a72784d6ea1744d6b0b91e7ab66baba
- pocketmine/raklib 1.1.1@be2783be516bf6e2872ff5c81fb9048596617b97
- pocketmine/raklib-ipc 1.0.1@ce632ef2c6743e71eddb5dc329c49af6555f90bc
- pocketmine/snooze 0.5.0@a86d9ee60ce44755d166d3c7ba4b8b8be8360915
- ramsey/collection 2.0.0@a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5
- ramsey/uuid 4.7.6@91039bc1faa45ba123c4328958e620d382ec7088
- rhumsaa/uuid unknown@unknown
- symfony/filesystem v6.4.13@4856c9cf585d5a0313d8d35afd681a526f038dd3
- symfony/polyfill-ctype v1.31.0@a3cc8b044a6ea513310cbd48ef7333b384945638
- symfony/polyfill-mbstring v1.31.0@85181ba99b2345b0ef10ce42ecac37612d9fd341

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwlz48aV/isdaaqs2RAUbpJKyTWTkexoM4d2pIm9MV1yA2iQsECAxiGJdvm/7/deN0CQ0ozt
JJva2nJN2QQa3a/ffXXrp4O0rFayublTVZ2VxcGJPzpospU6OHEmnm/PQj8IxqETuN5sdNCu9Sd7
7Pmebfsz35n5tmdPwtFBLuvmvKrK6uDkp4Nms8a0g0tZ1UoPjg5Wqq7lgobrTdHIB6How0i0hXpY
q7hRicgSVTRZmqlKzA8u359/cfH1/GAk9PesWGD0dH4AWGmb519kOQFbL2V1cnx8vCxX6jguATkr
VHW8zttFVtTHf2+rbExzjusqpu9ptjh+xT+XslnW+LYmgAbYr1yFFTm2OTjxArCrkjEevzk4tMV6
RQvov2ZZKZkcX/PPlUzVK3Cofl3KRFVHjus9PxHrMr5VzQqA5nM9fT5/cr71eY5fHjiqmwqc+Mbz
vxXvVVakm2slV/M5YTyfa0zn8wGqz4HroSN+BWVvZAH5VEf+b8Ttqak/xXlZt5X6+R/D1/3VjPQI
2ayI8zZR3V7h7Fvxj6uFYQMpBuPi/RuFGv4ykwx6jJr/EbHS28tXQMj/35Dkb0QyGPBPo3t8yT9/
lrU6mkyA4mNwmgLr87Ig3I4YUPgxQJ3iuo8EoKfN59sNrc9vboAraGnj5qiMvodneXoJmKmXae4c
BsHU9UfiiSVXqoL7PHS8J7/u4nCm6rjK4EfL4jDwPH82Eh1f3W/F0+p6k8hGslD7yb7961X8k1id
ZfXte1WXbRWry6q8y5hUL5z6zPPJL/HcmwSf5LmZZ32eFY2qCpkTN/WnXqG8jxH+a4n4DbL6BWkw
0dMB0Vq2Rw6C3a+jM+/p683a9T9O4AjOqxE27zsb7HvJO73B3CMv2GexRuoXVfmT1n4YPsmftsny
ej5/I4mXC1B06PZK54SP6eg/fopIHYPsj5A3me6RV2ue61XOI6jbtdabS1aOIyckGJX6oc2qPgxM
3K2NNKv17jqLvlixjJdqbB9fvnlz+WUTpJc/jBvjQ7ezdST4FoGe+Yg0gbhz8PPoQP3b8p1/Jj3Z
x3p3YGSg3mTFXZnfqRVQwrcEjIyb/itG8ByXiSJy3RDv4j8w4k76pyk/HdPjTE/3bAKk4lwaocTN
DXGqPnWe/4m+O2aei99CgmFrZFIfDS68xDNLfPzKqKbcqxExqbUYMED8RHMCzJk36zbKs1iwpRhl
FZrX4hQM/pF5Wak0e5gf8Bah2WLy0eUv315f/Pnd9c2b86url1+eb+FIiDMqm7GRvQE4/Sig87OL
64t3b794+dfz94+hqSQjz5TKW6QjuyANh337o6Dfnl9/9e79X29eX7y5uN7CLFRzX1a34zxbZY0G
5ju/DsjN+duXf359/hiWKmSUG8x89xeBPaKzg7NDom8k7fsfl+LF2y9v3r57/+bl64Eo8WVcUFGT
G0DBpwG8fvnll/jdg5DLBdR+QSB+/j3F/z3F/z3F/z3F/z3F/z3F/z3F/3+d4htyKMl91dZNubpa
lusPF/ROCSoyiZ3h0UHfNz0IxvY4wIhsm2VZAcQ3gCfXGaUN9M0m+DpVQvKdyrxWI2THa1UkZnJd
ps3ZcGAlOfN+mauHS5lAZsPNtQQp1S85m798d0X51eszDN2rqM4aQlcn/OpqLe+LARX90JAC9xEF
B3W7VlVcyRSW7SH5/leRtAeXFFkjtH36JcqWTbOuIfg9UONF1izbaJyVxx2k44OfwYW1rEA7JjFh
4yd0DOAtqyit++xHWSX8lmQ1UWfJos6Y2IdGFcQurSJlRZhMx+7YJcbBie+851n0sMqHIyVYUdc7
Q+t4F0j9Qw4CveHQjwA0fJdVJTeJitoFRm2M2hiM4hWSq+G0WOZgPOgaji3b4pY9gMtrPZZ4XG3W
TWkGXBowFe12XVvtYJ2UK9IY2/YcB/Xe6OD7mnWon0AlK0J+uTcG/u+MNOvh6yLZeVvtfFzKeoe8
upFE3c6Sq8vXOwJQdypPIkOYrUWSqDTXgiLWOVSqR9qfDJeuyqphiuyxwyxZbSCZgnYzT2I7lway
XaEWzQ6/skWUFbLaYMyjXcMDshwU1HrbDr3Ls3c7YJLyhoHvD2olGY5SgNzhDqt3vbNwtVr3xX8I
smjHdVlnD8NZFbjKwt2OKEiflH7RanbbZu17cJI6FbuSr5erckdwV9lqnauv3+yIpilvVZH9uKsO
e9aCV8L20Zz7KtvTo4cHox2dNWwkg8LnsU8WlBFGEKTDAv877EK8u+TYsAUDJ/F91tysuMtRtHkO
7izXRolJHxVik8wHbnTHh5ANIv28GYYE1+P9ojbLwTiYyxSqUN8k6q73l+uqbMq4BNhJGGKTjNov
bmQnUkWxKyfuZOonoZLOxMdvZEczR01kFIaRjCRgtwaX11nRPgjXDsNg5sfWZOq6lj/xplaEVMlK
osi3J4GduEksgrED9205jmcxTaiLD1HaWB+itmhacfXmUrwpC/GfbSEQ0u3piROeOBPx4foV4Lu+
eJiGNyGxlQ7Phn5KsX34vcIt1zdl3eFG7o9ecvMSlyson6puYJOVrDLFPlUmS3CjUsfkUCzMMQ0p
h6zmRRg4tuuls1QFrpqpVLrObBpHMg2VP3USZxZOletNJsRzkHV7bHwiNJaWp1ge29K3Z44z84Jo
Momm4TSYqShAZZEE0yQM7SR12JdDjmwKx/CjeSTjW+tO5hl8PPX8wPbborwvXphfrChUU6laySpe
MvIruV6zlt5xrHwxjUM/mSa+78sgmYQ+Xh0VqdlE2cqL4okbuUGUhjEbZZcqHUcqqfBmRTn9v10v
KhiEVUNxV9JkHfYL106SIHYcNZs5AVBV0k+VG6ehP1NO4nrhbCJDsOxp0FR7sK2QVvyxG2VjCewX
oZo6s9QLk8nUmYZhrEIvcX07jLCBmqRu4sg0mcnkadgw1NVjrGGFPtCepfEknkURaai0nYk3AxFx
NEkSbBnbnqfAHSeKnga9NZwDj9nwCPUocVQ8mUVSTePpVMrZ1FdOHKR27HmOF6lAqlnke8EefHbU
HCONQwlfxHEaO9PZLIKyJH4wdXwlvWDmKteGCGMfSHtOPPV3IT2pOHCdY+9F6E+mEx9ygR3HUk5U
MJ0Gru+qaRC7XuwGQDkI5J7EQC3DoHDhvJC27zophK7syI5DaLRtp9HMTYKZ5049ZN1pKAPl7MLg
NvQSmp0rDWoCScTghD+d+qgK5cRXMXRl5kezNJ2kKnWmEw9uI5m5e6Cgkkgxtvrjwve+kCoJfTWL
5cxN0yhy7cl0Gnn4F02CKLSVn9pKKjfZB6XDIKmFCuOZ48Z2OrODIJ6SAjv2VMVQNQhzFqa+7ce2
7+1CMJbusEEksQOUYeKzIPLgKVLXsaHAkRfDAL04DF0wJonSXRBF1PQQXDvwbXcCdYR7sP1w4saR
A9WP5cTzwjAFXbOJn+5xZPtocfICR28hT0EK+eI3uPQBwEre6uQPJgORw+gmU9JcJ4SrUO50AiYT
jyB324dyhqEziWaTp4BY2To25DkvyIxdlbpxOPE9NXFUkkRBEnvuLPZncKdBEID90Z4zqouy/FFn
TgGJehomM6VCO1a+PwmCxAnDxIsnkfSjKf6pqRfC1eqsYlWrDSnwNmNwmdGY60/hDiMoyzT1ZCh9
uBQVOTAweAZoN8I0XOYWSNtmOsxMYJkzx/ZmUeykUvpwfQhjsQ/tnwVTFcItelMXLsCeTmn5sl3V
UnbrH3vwerNKy2JzTLlrvanhush7h1BKx3sB7kIv4zSYBkkgkfd6cOZeAOcXTh0ZuGFqe9Mk8QZw
1mW+Aazc6tLpO2fsOUSzF8fTyEYkgBYEDryRHUeJP1UplAu2MvVnfhB606dgDZLVDtw0cKZOJOGe
XA9MsGGyJBKXOOdNQgeWkCae7+g6qBfneMM50qGgQlLo9l5bSZKOIBaItKzEToozLw7F9RJBTtSq
oROqWshKCRRaoixUjQfZiFgWRdmISHVN2wQPQlf8YzhtBMUGwZ5gXaHsF2VKAPZh1jJVI1HiS1UT
SBEhFbwVm7KtDCyRpQK5Gp2f0Q5IGujIKt8Q4Lfqvgd3jIRftnlTi/uy+KwRFJZlJVDllvAZGTnp
DWHYLLNa032/VIXQQYvOAubFvOiAncwLIQ6/WipCTDQldkEqCRCmSQIeIGuoqcBI9GdGVXtKAX7m
qmF+wTNksRLaEdPIiiCD47Gyckmp9kKdCM4R6UO9bJsEWmqZQ5ITMT/QPSJB3VuVzA8Ys5d5Xt6L
PKv5/NC0M8RdJsV/tara0Jwf6MEyn06Ab8s7HJ5zIW/WCOAlKA8TkBiYQtCijTCspPm67rf6zwNk
D7+CokIjwFeZJAJZkWY/sRUMvxUrJanhTKmdANMjRUiDOeqHVubEtkV2h7kIm60SR2ZT5J7PCbre
UVmVWqNGs8B2amKd4DPv/bZdReAKtOplvSnia1nfCjpegh6NecIHcItVu6OUpi2rsihbSA/T6xEt
yBOhE36yh5GgbBWEUGbPvLlXEY2t2gIaRFM08CsWL2iCllXlQwYNU2ADSGLNLXrkiLcGoYuUdJXm
kE6ORNZ8BvY1FS9LVEMNPFKZvcXiCDS0sBuX2cJkWIbSEwa1r6uSlaNqi4LEmVBxXK5ZCFyg1GNx
pu7Ms1hliyWMuUJdNRoan1Ec4khVtetGj2qGEWNQOCtDFwsXRslJfKINQt6VWQK0n8aAdIR0rgSj
oV3jgaJRKNWTek2bFyuF7TbaKL/MywjaQy0noccFn3KSba/UQkabBhwXV5rVNjNXt3d4+TVJ7T5j
zrNGwWjvLQ2oU7KaKUwzoAiPBOwLhpVWSnVbaiWHtFoyU7EoIaiSzJS0gjZaMJoWo3YibKICu7ML
1sX5/3kKqIf3KfyXskr+OfzrplwzCsZ99igZcLWA+1jLmvxehxDt2mGFItE3iLET+IqtwuBXf/Yv
wJDtglEijyHiFsGnQPAR6kHFLTvfUqOsLZKCVT9bPcRKJfWWIu243l2fn4jrv1xcCX1o//Ly8vXF
+ZW4PH8v6OT8/P1IYJK4fodZ5+Krv7x7fS4u3797dX51Nd53ATv8cIPQsOMS1X7JAZkccU0Eoihj
l8zc6J2tA94jJUjYt/AUC65QaTfLoF6VBeiEg4Y2Eb0fUzatZPdLiqzgCbkgPY0hayBwvVtHriMS
7/GOYgjFeV4wfjybdMF0oCG2tYopHdCcJXS1XPXangaol1rXW1I929BaP38aJUO5ZyhfyCqCZVjb
ZJYd0NPcZVMjdMwqYVbBd69k0XLyMcQEiVkLHXw+6mLCvhJ2aqjDa5oClqZ3tTXBsXinfb5WeGQP
ZZsnPS4Zgsh9Ibb41xrwmtEHoaFtG1qx2xfsLB4FSVYdDaGnLa3KVRds9Wozwxqq5lDCRI2R5CPd
EE+o1I52XHUJI4mswk6khkaRk3a11tmVTuGE+WDRh05eZzTJLGDcGc2OArwhzMPY5RMMRtBG4MMO
d1Cyum4VOYZmCaktumyTnBbttsVq1AlS5wgmqRxrbGjqR/m0kg8W9+7rDvdXck2j2apdIcYivFYE
vJEFskoIEnFabjrXueUr2YthJVvMYx1Dsr02GPGGFmXBLYKu30vsrNSf9nWaciPyehq+ntyZkIZl
Jg4p48xBH9P1tJ0BFc5VkD4S94CdTjA0lLWkmkToNZrCLXVYZvhpzm7MzjR5m+0SA3MqAwzcT4P6
lB7OC3N/6cSECKRmyzLXKWYkm3jJmTijXNNZsDBBhn2brnzMVx1aItUnmzq8HQ6l1H0it1ptGgI+
EpYzECALjze2mg4ZEwLYa2/zWD4eoRQy0ZRTLcOJPi3GoEFrLP6CXBC6dMrJnXh1+WGEtcAhgn3d
ZwnUnnMF7T17+BbDPxFhl3ZvM/KauTPMqZOWg0hvZwu5ovDPH2FtRQyzw6ugyqqIYUlRiyRJbqD7
SRvvGKegc8NtPBzsMqxRdgWlDX8w9ZGkOhnlslqwa5WmZHwstB1vmbMvg6tRJCNezenUkjAdVimj
x0hACalihXaBxchSKHFAxk0Ia0AGqSeJHUrfsdmjU5X3QF6eUm6ZjwUJ5cNlcdkVH9uCmGor2uge
aQQtbNfF2jLve9XeG+OF6uxH1XONSOtYVlMCYFJIlDHaXAaphj9z9aLnY3H5C2zmHdNKLogEsBqs
qNc5Z3BUbq+APDk/WZHevsozzNL9A7o6oOpGvLn+wJjWIInIJj2ifgWr9nY7XWyNO9+7alqLVp0w
tsN6GdpIp6fs+1JBjRI+jO7JbPCWZvFYcNReSkqKRLZa08VVrIE0+E+w4La1TkN8d4z0kjiBKMSB
CSmL5PBmTEKnVpjbGJslSpTulxjXb6rLs3ecNJ5dXPHtTc4v24LNlwJYS5GDj1J10pSRcZq7wMmw
/trSufV9fAZ90hWxnwuHileTwi/hvvm7MC2LWjdZFN/BLHUyYzyEQ8A01hraq2VZ1tyI6WpX1XUn
OKpRy1nU8q6LnnhUlv7G7ehBWwOI0fNIJ7GmR/V9mRW6QcKc+kx8HZUP5AkrcXEmjr7+cHH2HHKH
GwQOmH8PsZFgMjZormmrxPBHp2OwhnIruwLm9/WfX3fwTb07GPmMN+NLz9wmIvGa1IxpK7uOmUkr
HoCfRRczTss05W3xLUs31kObJVuBMD+t3WbVNXebtKnpv/bTPODIZ+yqrU3Xi9xso8OOWWPpNSfC
HKbTNjqkmnBhdqGcQBaLvmbTd3D3U5NRN+suU/dWn7A81SDUzH25KlvyHqmO/caZgGUdaynXoWyb
W0MQPz1zsoLF7zl1GSxmwgulWxGR0sAilZLt13RXpItBGjqrFg3vJkGafNqoJ//RTrIC3ogEncZi
vw5L+u0BentNKz7nI1Ops0QJswd1RCV0pm6jISELygswQyU6G+CXPlpz98zIV8axyhUXP1pDedc8
u8UWVPqzM8klmLGoyvtmqV0RtpBiqaEN/BQMuG50lsHIWsT2DjVrKwNN2sVZPaCLPC0JT0MT+oS1
J9N00brMTZ95DvkMeBZQROXfv2Wx6p+pwNkKaNu+O+ni1FjIfX0yTuleZly1I0joSB1RG2rd5p05
mBcKrDzHhAPPpQ253CPSeSeKpOSRkPqYQopGTMPyxKR01F/lJoIe1hkRtD8mB18stp432TozsjiL
/gpjb6g3+N1hc3thEKth55a+ONXPXEKYJxqVMd0QGWclYwwXtllREQwTbaifHNdb1Cn8mO9i+51J
YPclF4tKLUzr1PRZdTuJrtLf7tPH+MGHvDt7R3f8LOPsddwnt3SvdKUlYbz3vGPNiG8J4LHx4HAD
8bfnfLumq1laOI+YCoHq70bDkOHQxQOOUYM48orOINSwZ4mELV8vJWxFkceuhD7pG+smtUpVhdzU
In9XUJDTX7uYpCOC3OmBmpsjgyDaotZAzsI+s3NNBiBLWX/v9ngkVU3XUKxNttpGBhNlCSjNJ62n
QEBSJPdMG3Jz1yzqGvnj7Qbmy3CHjnOPms8x567UDJakQHQmMcgGuKI2hp+As4WubQSdnCVdL83M
7VPubIEo04Vh5LJpy6cHZHuELF95pk6JoGSbU54+qHKfeQiTcj7yoroeOlLjxZiJxIteNBJnpF34
VU08fj5IjbJi3TZDVflY9mJCo9ZfbfeDTmGHSZM1Rou6nuDSDGpvX/X0d/wSZGyVpjBLe0B0XaCt
9HkaOd6uUaaDEOAZR91lD8gwqcbSotNpTW3Kei7HdcZIskwgogoF8R2faeFJrjvJCgNFE3D4UpCi
Axke5kycCgw6L6SlnHXrrLXXDDrXMECed1D0K+UksO1EsPSYC1RWVBQqoTH7KAjzx2cJHV11Z2H7
Z5owtlrl6dj0lCiRMZTJQgPSrbiM7eObb1H6UthEtncEniodifUfkKntzjxnPjhsPaGe9vxAI00M
687YJCo8vXOkzM7Jcy0CWnKCLTvUXnUc6gRqpo90M1Cnjx37xX9DVsRuuGbeMjV22HNJu6CMQk+L
GUcdEc/1bpScjjhdIJ0imdHUjkBCgXhPd/FQg4xZSRkOrSNramvd3azLldK2/JgpBhVaAt6Uld55
bu5h0/DuFK0OMqI4Kr7Z4+63AxHSueNWfnQeakyMgR3Vz7Xcsoa10ag81SyYZdwwNjBP3+qv8CpG
IlxuYN1I7O9LldMtqc6OTuscHhVtS34eCJGbfcZNGzrFYNSQuwDJbs5IPHPZEetTEOpOk9vReNLp
qExAN1Ap1wD0LTYX3/XDIFs9fCesz8V3+MwvvO4WikDYt1kMiwHycgNxXFCPTmfENAHg5gcaIL9u
YZl134k/4vnJpTR3fvBdj6RO77AlvRDBz9xuVzr6Jx9ABfH3bU26HCvMopT5mfuHDoUtFAYOj4cE
rkg0Qgx1d7hH7VPwzew/MKq96FaSBNfJiLrzfGVrI45g66wtAw1CypLltTnV2fQGudZ/X5M8NyJ+
BgOiQPLsGUrjZ89cLT/aaSi/ToD9+BMCHA0+f6f1qSgH6J7qvy8e0GM0C3XIArpHqfaCL1sM1HBN
Sb6wxNFys0aa9VzwLXqmM0PZ9qDRbdZsRkC2IWWzNLJmlBqLYmLTj0YYc3aGdBbHh3X1AF+nOxsy
TUyztfayhAAAfddxe0CVKR/p8PLB3HLY8fr6DJpECVBJOfA+yI9UR9DWCth4dSncl8vDuyi7QYYP
cnRZQfmeap6sXIXGhiMm9SL5AACZU7bOlSm7TS9O0s1ovS+P60dApATVt3UVu93xRHzx+uW1HqQ2
n6KzvT+Za4+jYPYAd1SokfeQZFUz4jrpT6a3om97DI9NtGCI2wj/5lRTtiYfzJFQxBuh//KorbqK
qOsVV/09EU73ScC5jPkeTt3xyerumMDedCPt8AvO83krnr8DhDtRYvD3cGbE4o7OoNVS6m4by782
bfb4lhqTNTdPUXZEWZ41G20mvZ4AlQZS4apEpyeaSoZvAcm+UKJ7V/tCpZtSl1sR67+C5PtC8+Lw
iyoTb8s74c6E7Z94zonv9Nel6fIQ/zFXtj61x/xvXpjMke/inOr8y8yipPAUphPM5gV/Hg9HVmWT
nO7mL/oa0M76u/DUmTme1++TrTFUkqYvs0ZZFA+pkQR48sH0zepTh2pV6rvTDfjTqw/v/3bxt5ev
54W+lNR/4HV0uky3UPTb+m7N0JOMWp3Q9M0pyuJebfv69LTrUFE0P2WN3/asVNJ/pqT/9Oz8i5cf
Xl+bEo5CLu+x0zg6dcJ5MeiNUQvMXJ46VVRkHvz8P9Kbhj0=
===END CRASH DUMP===

**Comment by xqwtxon** [comment]
Your php version isnt compatible with anticheat, please use php newer version (8.3 or higher than that)

**Comment by PSYCHO1512** [comment]
im using the latest pocketmine version i think

**Comment by xqwtxon** [comment]
> im using the latest pocketmine version i think

its not pocketmine-mp, it is php itself.
