### ISSUE TITLE
syntax error in Zuri plugin

### ISSUE THREAD

**Issue by GdedeQ1** [ReinfyTeam/Zuri#59]
Hello
I would like to use **Zuri as anti-cheat** on my minecraft server but when I put the plugin in my **file folder**, the server crashes and gives me this error:

ParseError: “syntax error, unexpected identifier ‘PREFIX’, expecting ‘=’” (EXCEPTION) in “plugins/Zuri-b7217d32505855d9532364d636fd3c28d5512801/src/config/ConfigPaths” at line 35

I've tried the version available on **poggit** and the version available on **github**, but the problem persists.
Is it possible to solve this problem? Thank you in advance!

GdedeQI

**Comment by xRodzMC** [comment]
You are using 8.2< php version. The plugin code is now on 8.3> php or higher. Please update your php binary.
