### ISSUE TITLE
False Detection: Speed & Timer

### ISSUE THREAD

**Issue by UnknownNull** [ReinfyTeam/Zuri#6]
Anti-cheat `speed `and `timer `are very sensitive

**Comment by rodolfoorlandajr** [comment]
Could you please detail more information about your issue?

**Comment by UnknownNull** [comment]
> Could you please detail more information about your issue?

The plugin misidentifies almost half of the checks.

**Comment by UnknownNull** [comment]
For example, Cheat recognizes climbing stairs

**Comment by rodolfoorlandajr** [comment]
> For example, Cheat recognizes climbing stairs

Could you please send the log in which `subType` causing a problem. It is better if you demonstrate it to a video.

**Comment by UnknownNull** [comment]
I have a plugin to create a `HangGlider` where I have the following code that receives a negative value:
`$effect = new MyEffectInstance(VanillaEffects::LEVITATION(), 100 * 99999, -4, false);`

And in Anticheat, when checking it, the server crashes!
Log:
```
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Zuri

Thread: Main
Error: Typed property pocketmine\entity\effect\EffectInstance::$amplifier must not be accessed before initialization
File: pmsrc/src/entity/effect/EffectInstance
Line: 103
Type: Error
Backtrace:
#0 plugins/Zuri-Rewrite-main/src/ReinfyTeam/Zuri/checks/moving/AirMovement(69): pocketmine\entity\effect\EffectInstance->getEffectLevel()
#1 plugins/Zuri-Rewrite-main/src/ReinfyTeam/Zuri/listener/PlayerListener(87): ReinfyTeam\Zuri\checks\moving\AirMovement->check(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#84371, object ReinfyTeam\Zuri\player\PlayerAPI#157385)
#2 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#155797)
```

**Comment by rodolfoorlandajr** [comment]
> I have a plugin to create a `HangGlider` where I have the following code that receives a negative value: `$effect = new MyEffectInstance(VanillaEffects::LEVITATION(), 100 * 99999, -4, false);`
> 
> And in Anticheat, when checking it, the server crashes! Log:
> 
> ```
> A PLUGIN WAS INVOLVED IN THIS CRASH
> BAD PLUGIN: Zuri
> 
> Thread: Main
> Error: Typed property pocketmine\entity\effect\EffectInstance::$amplifier must not be accessed before initialization
> File: pmsrc/src/entity/effect/EffectInstance
> Line: 103
> Type: Error
> Backtrace:
> #0 plugins/Zuri-Rewrite-main/src/ReinfyTeam/Zuri/checks/moving/AirMovement(69): pocketmine\entity\effect\EffectInstance->getEffectLevel()
> #1 plugins/Zuri-Rewrite-main/src/ReinfyTeam/Zuri/listener/PlayerListener(87): ReinfyTeam\Zuri\checks\moving\AirMovement->check(object pocketmine\network\mcpe\protocol\PlayerAuthInputPacket#84371, object ReinfyTeam\Zuri\player\PlayerAPI#157385)
> #2 pmsrc/src/event/RegisteredListener(61): ReinfyTeam\Zuri\listener\PlayerListener->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent#155797)
> ```

Hmm, its looks like the player is not loaded yet in the cache, and also what the hell is amplifier is set to negative value? It can only ranges only `> 0 but not >255`.

**Comment by rodolfoorlandajr** [comment]
_Hack-fixed._ Checks should probably run only if player is not null. **Thank you for reporting!**
